### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by jefersonbelmiro** [troydm/asyncfinder.vim#2]
my current installation does not have +python, but has +python3.
It is expected to change, or have support for both versions?

**Comment by troydm** [comment]
hmm, I haven't considered supporting python 3 yet as it would mean I would have to rewrite a lot of parts to asyncfinder, sorry. Not sure how to go about this as it seems you need to recompile vim with +python support unless you have some points not to do so.

**Comment by joeytwiddle** [comment]
I can't get homebrew to compile MacVim with `+python` support, it seems determined to only provide `+python3` support.

I tried `:%s/python/python3/` but it didn't work. lol! Worth a try...

Apple making more work for troy. What a suck!

**Comment by troydm** [comment]
@joeytwiddle why not just download MacVim's distribution from Releases and use it https://github.com/macvim-dev/macvim/releases. I'm using it and it has +python and works just fine

**Comment by joeytwiddle** [comment]
Thanks for the tip! The latest download version of MacVim comes with `+python/dyn` and `+python3/dyn`.

One of my plugins (UltiSnips) was using python3, after which Vim refuses to use python2. But after I told UltiSnips to use python2, both plugins worked fine. 😃 `let g:UltiSnipsUsePythonVersion = 2`

**Comment by troydm** [comment]
@joeytwiddle good to hear, I'm closing this issue
